import { ThemeProvider } from 'next-themes';
import NavBar from '../components/NavBar/NavBar';
import '../styles/globals.css';
import Head from 'next/head';

function Provider({ children }) {
	return (
		<ThemeProvider enableSystem={true} attribute='class'>
			{children}
		</ThemeProvider>
	);
}

function MyApp({ Component, pageProps }) {
	return (
		<>
			<Provider>
				<Head>
					<title>Matias Palomo | Front-End Dev</title>
					<meta
						name='portfolio by Matias Palomo'
						content='Generated by create next app'
					/>
					<link rel='icon' href='/favicon.ico' />
					<link
						rel='stylesheet'
						href='https://cdn.jsdelivr.net/gh/devicons/devicon@v2.15.1/devicon.min.css'
					/>
				</Head>
				<NavBar />
				<div className='bg-gray-100 dark:bg-zinc-900 tansition-all duration-700'>
					<Component {...pageProps} />
				</div>
			</Provider>
		</>
	);
}

export default MyApp;
