import NavBar from '../components/NavBar/NavBar';
import '../styles/globals.css';
import Head from 'next/head';

function MyApp({ Component, pageProps }) {
	return (
		<>
			<Head>
				<title>Matias Palomo | Front-End Dev</title>
				<meta
					name='portfolio by Matias Palomo'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<NavBar />
			<Component {...pageProps} />
		</>
	);
}

export default MyApp;
