import Head from 'next/head';
import About from '../components/About/About';
import Contact from '../components/Contact/Contact';
import Main from '../components/Main/Main';
// import Image from 'next/image';
import Projects from '../components/Projects/Projects';
import Skills from '../components/Skills/Skills';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Main />
			<About />
			<Skills />
			<Projects />
			<Contact />
		</div>
	);
}
